FROM java:8-jdk-alpine

COPY ./target/codingchallenge-0.0.1-SNAPSHOT.jar /usr/app/

WORKDIR /usr/app

RUN sh -c 'touch codingchallenge-0.0.1-SNAPSHOT.jar'

EXPOSE 8097

ENTRYPOINT ["java","-jar","codingchallenge-0.0.1-SNAPSHOT.jar"]